- name: Ensure chrome dir exists
  ansible.builtin.file:
    path: "{{ (root_profile_directory, 'chrome') | path_join }}"
    state: directory

- name: Copy userChrome CSS file
  ansible.builtin.copy:
    src: "{{ firefox_css_src }}"
    dest: "{{ (root_profile_directory, 'chrome', 'userChrome.css') | path_join }}"
