- name: Search for sub dirs in profiles dir
  ansible.builtin.find:
    paths: "{{ (lookup('ansible.builtin.env', 'HOME'), firefox_profiles_path_component) | path_join }}"
    file_type: directory
    patterns: "*default*"
  register: firefox_profiles

- name: Found the following profile directories
  ansible.builtin.debug:
    msg: "{{ firefox_profiles.files | json_query('[].{path: path, mtime: mtime}') }}"

- name: Set most recently modified as root profile directory
  ansible.builtin.set_fact:
    root_profile_directory: "{{ (firefox_profiles.files | max(attribute='mtime')).path }}"

- name: Root profile directory
  ansible.builtin.debug:
    msg: "{{ root_profile_directory }}"
