- name: "Arch Linux laptop configuration"
  hosts: localhost
  connection: localhost
  gather_facts: true
  pre_tasks:
    - name: Check if running on laptop
      ansible.builtin.assert:
        that: "ansible_facts['nodename'] | regex_search('xps')"
        fail_msg: "hostname: {{ ansible_facts['nodename'] }}"
  roles:
    - firefox
