- name: "Arch Linux desktop configuation"
  hosts: localhost
  connection: localhost
  gather_facts: true
  pre_tasks:
    - name: Check if running on desktop
      ansible.builtin.assert:
        that: "ansible_facts['nodename'] | regex_search('desktop')"
        fail_msg: "hostname: {{ ansible_facts['nodename'] }}"
  roles:
    - xorg
    - firefox
    - golang
    - zathura
