- name: Disable Display Power Management Signaling (DPMS)
  ansible.builtin.template:
    mode: "{{ etc_mode }}"
    src: "{{ xorg_screensaver_conf_src }}"
    dest: "{{ (xorg_conf_d, xorg_screensaver_conf_dest) | path_join }}"
