- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
- name: Setup version management ({{ python_pyenv_pkgname }})
  ansible.builtin.include_tasks: "pyenv-{{ ansible_os_family }}.yml"
- name: Setup depenency management ({{ python_poetry_pkgname }})
  ansible.builtin.include_tasks: "poetry-{{ ansible_os_family }}.yml"
# TODO: LSP setup
