- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
- name: Package installation
  ansible.builtin.include_tasks: "install-zathura-{{ ansible_os_family }}.yml"
- name: Set as default PDF viewer
  ansible.builtin.include_tasks: set-default-pdf-viewer.yml
